# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jokes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jokes

	  pod 'Google-Mobile-Ads-SDK'
  pod 'pop', '1.0.10'
  pod 'Pastel'

end
